---
title: 'Problem Set 1: Predicting Income'
subtitle: 'Big Data y Machine Learning para Economía Aplicada'
author:  
        - Gustavo Adolfo Castillo Álvarez (201812166), 
        - Alexander Almeida Ramírez (), 
        - Jorge Luis Congacha Yunda (201920042) y 
        - Jaime Orlando Buitrago González (200612390)
date: "03 de marzo de 2024"
fontsize: 11pt
geometry: margin=1in
documentclass: article
papersize: letter
lang: es

header-includes:
    - \usepackage[utf8]{inputenc}
    - \usepackage{floatrow}
    - \floatsetup[figure]{capposition=top}
    
output: 
  pdf_document:
    number_sections: true
    fig_width: 3
    fig_height: 2
    fig_caption: true
    
bibliography: References.bib  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#source("../scripts/00_packages.R", local = knitr::knit_global())
library(knitr)
library(ggplot2)
```

# Introducción

@R-base
@geih

# Datos

# Perfiles de salario por edad

# Brechas de ingreso por sexo

# Predicción de salarios

# Referencias bibliográficas

<div id="refs"></div>

# Ejemplos

Para incrustar código y resultados de la consola

```{r cars}
summary(cars)
```

Para incluir ecuaciones

$$
w=f(X)+u
$$

Para incluir gráficas

```{r echo=FALSE, message=FALSE,file="../scripts/Code.R",fig.align = 'center', fig.cap="Título de la gráfica", dpi=300}
```
\begin{center}\footnotesize{Fuente: Cálculos propios a partir de @geih}\end{center}

